[project]
name = "altbuilder"
version = "0.2.0"
description = "Tool for managing ALT Linux sandboxes"
authors = [
    {name = "Aleksandr A. Voyt", email = "sobue@altlinux.org"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "click (>=8.2.0,<9.0.0)",
    "tomli (>=2.2.1,<3.0.0)",
    "tomli-w (>=1.2.0,<2.0.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "rich (>=14.0.0,<15.0.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "typer (>=0.16.1,<0.17.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
altbuilder = "altbuilder.cli:app"
