branch = "Sisyphus"
arch = "x86_64"
mirror = "http://ftp.altlinux.org/pub/distributions"
# Alternative: use local repository mirror
# mirror = "file:/mnt/repo"
mirror_task = "http://git.altlinux.org"
rdb_url= "https://rdb.altlinux.org"
packager = "User <user@altlinux.org>"
base_dir = "/home/<user>/.altbuilder"
environment_dir = "/home/<user>/.altbuilder/environments"
build_logs_dir = "/home/<user>/.altbuilder/builds"

[sandboxes.Sisyphus-x86_64]
mirror = "http://ftp.altlinux.org/pub/distributions"

[logging]
level = "ERROR"
file_level = "DEBUG"
rotation = "10 MB"
format = "{time} | {level} | {message}"
max_files = 5
